### ISSUE TITLE
Shadowfox theme not being completely applied to about:preferences options

### ISSUE THREAD

**Issue by DukeValentine** [overdodactyl/ShadowFox#97]
This is something I noticed just now. The options for languages and fonts still have a white background  with a black font.
![screenshot_20180315_190456](https://user-images.githubusercontent.com/25365649/37493527-fcae1c02-2883-11e8-9bc6-5986ffa5644a.png)
![screenshot_20180315_190516](https://user-images.githubusercontent.com/25365649/37493546-0de9a4d2-2884-11e8-8cad-4c4dc8bba7ed.png)

**Comment by overdodactyl** [comment]
Thanks! Should be fixed now

**Comment by SW1FT** [comment]
Proxy settings still have this issue:
![proxysettings](https://user-images.githubusercontent.com/6627739/37548096-792d35d0-296d-11e8-99b2-fe1503cbffd2.png)
